[package]
name = "tinyrigel"
version = "0.1.0"
authors = ["Nicholas Benson <nickjbenson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Compile as a dynamic library consumable by other applications.
[lib]
crate-type = ["cdylib"]

# Internal lib strategy
[dependencies]
bindings-windows = { path = "bindings-windows" }
windows = { git = "https://github.com/microsoft/windows-rs" }
image = "0.23.12"

[features]
rust_analyzer = []

# # Direct import strategy
# [dependencies]
# # winrt = { git = "https://github.com/microsoft/winrt-rs" }

# [build-dependencies]
# winrt = { git = "https://github.com/microsoft/winrt-rs" }
